nodes:
  n3:
    modules:
      ballot_maker:
        name: ConditionBallotMaker
        conditions:
          # will not make INIT ballot when height, 13
          - condition: ballot.next_height="13" AND ballot.stage in ("INIT")
            actions:
              - action: empty-ballot
  
conditions:
  all:
    # base state
    - current_state="booting" AND new_state="joining"
    - current_state="joining" AND new_state="consensus"
    
    # got ACCEPT majority for height, 12 and round, 0
    - m="check majority" AND height="12" AND round=0 AND stage="ACCEPT" AND is_finished=true
    
    # got INIT majority for height, 13 and round, 0
    - m="check majority" AND height="13" AND round=0 AND stage="INIT" AND is_finished=true
    
    # new block created
    - m="new block created" AND block.height="13" AND block.round=0
