global:
  modules:
    suffrage:
      name: ConditionSuffrage
      conditions:
        # set proposer to n3 when height, 12
        - condition: suffrage.height="13"
          actions:
            - action: fixed-proposer
              value: n3
    proposal_maker:
      name: ConditionProposalMaker
      delay: 1s
      conditions:
nodes:
  n3:
    modules:
      proposal_maker:
        name: ConditionProposalMaker
        delay: 1s
        conditions:
          # will not make proposal when height, 12 and round, 0
          - condition: proposal.height="13" AND proposal.round in (0)
            actions:
              - action: empty-proposal

conditions:
  all:
     - current_state="booting" AND new_state="joining"
     - current_state="joining" AND new_state="consensus"
  
     # move to next round
     # {
     #   "level": "debug",
     #   "module": "proposal-timeout",
     #   "count": 0,
     #   "limit": 0,
     #   "callbacks": 1,
     #   "elapsed": 15.210288,
     #   "m": "callback executed"
     # }
     - module="proposal-timeout" AND m LIKE "callback executed" AND elapsed < 50
     - m="check majority" AND height="13" AND round=1 AND stage="INIT" AND is_finished=true
  
     # new block created
     - m="new block created" AND block.height="13" AND block.round=1
