global:
    modules:
        suffrage:
            name: FixedProposerSuffrage
            proposer: n3
nodes:
    n3:
      modules:
          proposal_maker:
              name: ConditionProposalMaker
              conditions:
                  stop:
                      condition: proposal.height=13 AND proposal.round in (0)
                      action: empty-proposal

condition:
    all:
        base_state:
            - current_state="booting" AND new_state="joining"
            - current_state="joining" AND new_state="consensus"

        move_next_round:
            # {
            #   "level": "debug",
            #   "module": "proposal-timeout",
            #   "count": 0,
            #   "limit": 0,
            #   "callbacks": 1,
            #   "elapsed": 15.210288,
            #   "m": "callback executed"
            # }
            - module="proposal-timeout" AND m LIKE "callback executed" AND elapsed < 50
            - m="check majority" AND height=13 AND round=1 AND stage="INIT" AND is_finished=true

        new_block:
            - m="new block created" AND block.height=13 AND block.round=1
